export const IMAGE_UPLOAD = 'IMAGE_UPLOAD';
export const IMAGE_UPLOAD_ERROR = 'IMAGE_UPLOAD_ERROR';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_RESET_ERROR = 'IMAGE_UPLOAD_RESET_ERROR';

export const IMAGES_GET = 'IMAGES_GET';
export const IMAGES_GET_ERROR = 'IMAGES_GET_ERROR';
export const IMAGES_GET_SUCCESS = 'IMAGES_GET_SUCCESS';
