export const DATA_GET = 'DATA_GET';
export const DATA_GET_ERROR = 'DATA_GET_ERROR';
export const DATA_GET_SUCCESS = 'DATA_GET_SUCCESS';
export const DATA_RESET_ERROR = 'DATA_RESET_ERROR';

export const DATA_SORT_UPDATE = 'DATA_SORT_UPDATE';

export const DATA_CREATE = 'DATA_CREATE';
export const DATA_CREATE_ERROR = 'DATA_CREATE_ERROR';
export const DATA_CREATE_SUCCESS = 'DATA_CREATE_SUCCESS';

export const DATA_UPDATE = 'DATA_UPDATE';
export const DATA_UPDATE_ERROR = 'DATA_UPDATE_ERROR';
export const DATA_UPDATE_SUCCESS = 'DATA_UPDATE_SUCCESS';

export const DATA_DELETE = 'DATA_DELETE';
export const DATA_DELETE_ERROR = 'DATA_DELETE_ERROR';
export const DATA_DELETE_SUCCESS = 'DATA_DELETE_SUCCESS';
