export const LANGUAGES_GET = 'LANGUAGES_GET';
export const LANGUAGES_GET_ERROR = 'LANGUAGES_GET_ERROR';
export const LANGUAGES_GET_SUCCESS = 'LANGUAGES_GET_SUCCESS';
export const LANGUAGES_RESET_ERROR = 'LANGUAGES_RESET_ERROR';
